apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    app: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec:
      containers:
      - name: deploy
        image: deploy:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
